print('Você poderia digitar a sua data de aniversário??')
dia = input('Dia:')
mes = input('Mês:')
ano = input('Ano:')
print('Você nasceu mesmo no dia', dia, 'de', mes, 'de', ano, '? Nossa que legal eu também!!')
